### PR TITLE
foos_responses added

### PR DESCRIPTION
**Pull request by hvilander**
Sweet foos responses

### CODE REVIEW

**Review by mspicer60 — DISMISSED** [review]

**Comment by fruech101** [comment]
ope

**Comment by 20BBrown14** [comment]
Something's not right. The version you changed to here is 10_01_4 which is also what is in master

**Comment by hvilander** [comment]
my bad I branched before other things and stuff; stand by

**Comment by hvilander** [comment]
There you go @20BBrown14

**Review by mspicer60 — APPROVED** [review]

**Comment by 20BBrown14** [comment]
+1

**Review by 20BBrown14 — APPROVED** [review]

**Pull request merged**
